
import type { Metadata } from "next";
import { figtree } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.className} antialiased`}
      >
        <main className="flex flex-col gap-5 md:gap-10 lg:gap-20 py-12 md:py-16 lg:py-23">
          {children}
        </main>
      </body>
    </html>
  );
}
